service: riot-profile-fetcher

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 512
  environment:
    RIOT_API_SECRET_ARN: arn:aws:secretsmanager:us-west-1:279243015913:secret:riot_api_key-V5XtIu
    RDS_CLUSTER_ARN: arn:aws:rds:us-west-1:279243015913:cluster:rift-rewind
    RDS_SECRET_ARN: arn:aws:secretsmanager:us-west-1:279243015913:secret:rds!cluster-de8e9b96-be1e-41db-a6d2-72725559a600-ZukdIB
    DATABASE_NAME: postgres
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - arn:aws:secretsmanager:us-west-1:279243015913:secret:riot_api_key-V5XtIu
            - arn:aws:secretsmanager:us-west-1:279243015913:secret:rds!cluster-de8e9b96-be1e-41db-a6d2-72725559a600-ZukdIB
        - Effect: Allow
          Action:
            - rds-data:ExecuteStatement
            - rds-data:BatchExecuteStatement
            - rds-data:BeginTransaction
            - rds-data:CommitTransaction
            - rds-data:RollbackTransaction
          Resource:
            - arn:aws:rds:us-west-1:279243015913:db:rift-rewind-instance-1
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - arn:aws:events:us-west-1:279243015913:event-bus/default
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:ChangeMessageVisibility
          Resource:
            - arn:aws:sqs:us-west-1:279243015913:silver-analytics-queue

functions:
  riotProfileFetcher:
    handler: dist/handlers/riotProfileFetcher.riotProfileFetcher
    events:
      - http:
          path: /profile
          method: post
          cors: true

  fetchMatchIds:
    handler: dist/handlers/fetchMatchIds.handler
    events:
      - http:
          path: /matches/player/{puuid}
          method: get
          cors: true
          request:
            parameters:
              paths:
                puuid: true
              querystrings:
                start: false
                count: false
                region: false

  ingestMatch:
    handler: dist/handlers/ingestMatch.handler
    timeout: 60  # Increase timeout for API calls + DB inserts
    events:
      - http:
          path: /matches/ingest
          method: post
          cors: true

  computeSilverAnalytics:
    handler: dist/handlers/computeSilverAnalytics.handler
    timeout: 120  # Longer timeout for complex SQL transformations
    memorySize: 1024  # More memory for analytical queries
    events:
      - sqs:
          arn: arn:aws:sqs:us-west-1:279243015913:silver-analytics-queue
          batchSize: 1  # Process one match at a time for simpler error handling
          maximumBatchingWindowInSeconds: 0  # Process immediately
          functionResponseType: ReportBatchItemFailures  # Partial batch failure handling

  getPlayerMatches:
    handler: dist/handlers/getPlayerMatches.handler
    timeout: 30
    events:
      - http:
          path: /players/{puuid}/matches
          method: get
          cors: true
          request:
            parameters:
              paths:
                puuid: true
              querystrings:
                includeAnalytics: false
                limit: false

package:
  patterns:
    - 'dist/**'
    - 'node_modules/**'
  exclude:
    - '.git/**'
    - '.serverless/**'
    - '.vscode/**'
    - 'src/**'
    - '.env'
    - 'README*.md'
    - 'tsconfig.json'
    - '*.test.*'
    - 'node_modules/aws-sdk/**'