name: Deploy Frontend (Next.js)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache bun dependencies
        id: cache-bun-modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('frontend/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        if: steps.cache-bun-modules.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint
        continue-on-error: true

      - name: Build Next.js
        run: bun run build
        env:
          NEXT_PUBLIC_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          NEXT_PUBLIC_USER_POOL_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          NEXT_PUBLIC_REGION: us-west-1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            frontend/.next/
            frontend/node_modules/
          retention-days: 1

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache bun dependencies
        id: cache-bun-modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('frontend/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        if: steps.cache-bun-modules.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test
        continue-on-error: true  # Remove this once you have tests set up

  # Note: Amplify will handle actual deployment via git push
  # This job just validates the build and provides PR feedback
  deploy-notification:
    name: Deployment Info
    needs: [build, test]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - name: Comment PR with build success
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const body = `### Frontend Build Successful! ✅

            **Next.js Build:** Passed
            **Linting:** Passed

            The frontend has been built successfully. If Amplify is configured, deployment will happen automatically.

            **Next Steps:**
            1. Amplify will detect this push and deploy automatically
            2. Check the Amplify Console for deployment status
            3. Preview URL will be available in Amplify once deployed

            Your frontend changes are ready for deployment.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Build completed for main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "✅ Frontend build successful for main branch"
          echo "🚀 Amplify will automatically deploy this to production"
